### ISSUE TITLE
Move Entrypoint files to inside /src

### ISSUE THREAD

**Issue by davidzwa** [mkevenaar/NickNelson#15]
## Expected Behavior

Move files like index.js to inside /src whilst keeping the modules working.

## Current Behavior

-

## Possible Solution

-

## Steps to Reproduce (for bugs)

-

## Context

Developers will have a slightly better overview

**Comment by mkevenaar** [comment]
Fixed in #16

**Comment by mkevenaar** [comment]
:tada: This issue has been resolved in version 0.1.0 :tada:
