### ISSUE TITLE
Replace `typeof image !== 'undefined' && image !== null` with `!!image`

### ISSUE THREAD

**Issue by davidzwa** [mkevenaar/NickNelson#21]
Null/undefined checks should not use undefined string equality. This is a thing of the past.

## Expected Behavior

Replaced code will cover more than just undefined or null. It will also mark 0, '', as false. The new code does not tackle [], NaN (I think) as falsy.

## Current Behavior

Unchanged

## Possible Solution

Replaced code will cover more than just undefined or null.

## Steps to Reproduce (for bugs)

.

## Context

Developer knowledge

**Comment by davidzwa** [comment]
Might as well reduce welcome::execute with some nulldef util for more simplicity.

**Comment by davidzwa** [comment]
Closed in #27

**Comment by mkevenaar** [comment]
:tada: This issue has been resolved in version 0.1.0 :tada:
