### ISSUE TITLE
Add Jest test setup and CodeCov (+workflow)

### ISSUE THREAD

**Issue by davidzwa** [mkevenaar/NickNelson#22]
Currently many runtime bugs can occur. Jest testing can prevent a lot of this.

## Expected Behavior

Developing a feature should be validated through tests.

## Current Behavior

Runtime bugs can only be caught by running the code.

## Possible Solution

Set-up `mongodb-memory-server` `jest` and `jest-util` to cover the Bot with tests.
https://github.com/fdm-monster/fdm-monster/tree/develop/server/test

## Steps to Reproduce (for bugs)
.

## Context

Dev testing

**Comment by mkevenaar** [comment]
@davidzwa that is a great idea, I am happy to set things up on my end if required!

Would you be able to help us get started, if you want?

**Comment by davidzwa** [comment]
I will change the title so I wont have to cover all the code. Will add the setup 👍🏼

**Comment by mkevenaar** [comment]
Issue should be closed, once PR is merged

**Comment by davidzwa** [comment]
> Issue should be closed, once PR is merged

You are completely correct, apologies! I was a bit too quick.

**Comment by mkevenaar** [comment]
:tada: This issue has been resolved in version 0.1.0 :tada:
