### ISSUE TITLE
Make command permission checker dynamic

### ISSUE THREAD

**Issue by mkevenaar** [mkevenaar/NickNelson#24]
Not all commands should be executable by all users. 

Some code could be added to each function but it would make sense to define a const that defines the member permissions and check that before executing the actual code. 

If the user does not have permission an ephemeral message should be shown to the user and the function should not execute (obviously)

**Comment by mkevenaar** [comment]
Also the bot should check if they have the permission to execute the functionality required.

Something like this:

```
import { Permissions } from 'discord.js';

export const memberPermissions: [ Permissions.FLAGS.ADMINISTRATOR ],
export const botPermissions: [ Permissions.FLAGS.SEND_MESSAGES, Permissions.FLAGS.EMBED_LINKS ],
```

**Comment by Lucxjo** [comment]
I agree, however, for like the ban & kick, since they have permission levels anyway, we should be checking those instead of if they have the admin perm flag since moderators would often have those permission levels but not administrator. If that makes sense

**Comment by mkevenaar** [comment]
> I agree, however, for like the ban & kick, since they have permission levels anyway, we should be checking those instead of if they have the admin perm flag since moderators would often have those permission levels but not administrator. If that makes sense

This was an example for the `/welcome` message. Obviously the parameters changes depending on the function
