### ISSUE TITLE
Server Information Command

### ISSUE THREAD

**Issue by Stones8000** [mkevenaar/NickNelson#50]
## Expected Behavior
The server information command displays useful information about a Discord guild, such as when it was made, how many members are in it, and how many channels it is made up of. It can also include other information such as the number of boosts, channels, roles, and even display who owns the server!!
## Context
This can be used in many scenarios where you might need this info, for example: 
![image](https://user-images.githubusercontent.com/79322708/170355609-18550f4c-cef0-4874-a77f-f811d826eeae.png)

**Comment by mkevenaar** [comment]
:tada: This issue has been resolved in version 0.1.0 :tada:
